name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Generate Allure Environment
        run: npm run pretest
        env:
          TEST_ENV: qa
          BROWSER: chromium
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Download previous Allure Report History
        uses: actions/download-artifact@v4
        with:
          name: allure-history
        continue-on-error: true

      - name: Copy allure history
        run: cp -r allure-history allure-results/history || true

      - name: Run Playwright tests
        run: npm test
        env:
          TEST_ENV: qa
          BROWSER: chromium

      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with: 
            name: allure-report
            path: allure-report
